name: Integration test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 2.7, 3.5, 3.9 ]
        cffi: [ yes, no ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - python-version: pypy2
            cffi: no
            os: ubuntu-latest
          - python-version: pypy3
            cffi: no
            os: ubuntu-latest
            env:
              PYTHON_FLAGS: "-bb"
    env:
      CFLAGS: "-Wconversion"
      PYTHON_FLAGS: "-bb -tt"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "from __future__ import print_function; import sys; print(sys.version)"
    - name: Install dependencies
      if: ${{ matrix.cffi }} == yes }}
      run: pip install cffi
    - name: Test
      run: |
        python $PYTHON_FLAGS setup.py test --skip-slow-tests

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install mypy
    - name: Test
      run: |
        mypy lib/

  test_c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        cd src/test
        make

  test_c_i386:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install libc6-dev-i386
    - name: Test
      run: |
        cd src/test
        CFLAGS="-m32" UNDEFS="-UHAVE_UINT128" make

  test_c_sse2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        cd src/test
        CPPFLAGS="-DHAVE_X86INTRIN_H" make

